//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("seleniumScrapeModel", "FK_tblHtml_tblSearchSession", "tblSearchSession", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(auctionbaseUI.Models.tblSearchSession), "tblHtml", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(auctionbaseUI.Models.tblHtml), true)]
[assembly: EdmRelationshipAttribute("seleniumScrapeModel", "FK_tblHtml_tblVehicle1", "tblVehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(auctionbaseUI.Models.tblVehicle), "tblHtml", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(auctionbaseUI.Models.tblHtml), true)]
[assembly: EdmRelationshipAttribute("seleniumScrapeModel", "FK_tblHtmlLink_tblHtml", "tblHtml", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(auctionbaseUI.Models.tblHtml), "tblHtmlLink", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(auctionbaseUI.Models.tblHtmlLink), true)]
[assembly: EdmRelationshipAttribute("seleniumScrapeModel", "FK_tblPage_tblVehicle", "tblVehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(auctionbaseUI.Models.tblVehicle), "tblPage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(auctionbaseUI.Models.tblPage), true)]
[assembly: EdmRelationshipAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleType", "tblVehicleTypeCountry", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(auctionbaseUI.Models.tblVehicleTypeCountry), "tblVehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(auctionbaseUI.Models.tblVehicle), true)]
[assembly: EdmRelationshipAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleTypeDefined", "tblVehicleTypeDefined", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(auctionbaseUI.Models.tblVehicleTypeDefined), "tblVehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(auctionbaseUI.Models.tblVehicle), true)]
[assembly: EdmRelationshipAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicleTypeGeneral", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(auctionbaseUI.Models.tblVehicleTypeGeneral), "tblVehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(auctionbaseUI.Models.tblVehicle), true)]

#endregion

namespace auctionbaseUI.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class seleniumScrapeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new seleniumScrapeEntities object using the connection string found in the 'seleniumScrapeEntities' section of the application configuration file.
        /// </summary>
        public seleniumScrapeEntities() : base("name=seleniumScrapeEntities", "seleniumScrapeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new seleniumScrapeEntities object.
        /// </summary>
        public seleniumScrapeEntities(string connectionString) : base(connectionString, "seleniumScrapeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new seleniumScrapeEntities object.
        /// </summary>
        public seleniumScrapeEntities(EntityConnection connection) : base(connection, "seleniumScrapeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblHtml> tblHtmls
        {
            get
            {
                if ((_tblHtmls == null))
                {
                    _tblHtmls = base.CreateObjectSet<tblHtml>("tblHtmls");
                }
                return _tblHtmls;
            }
        }
        private ObjectSet<tblHtml> _tblHtmls;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblHtmlLink> tblHtmlLinks
        {
            get
            {
                if ((_tblHtmlLinks == null))
                {
                    _tblHtmlLinks = base.CreateObjectSet<tblHtmlLink>("tblHtmlLinks");
                }
                return _tblHtmlLinks;
            }
        }
        private ObjectSet<tblHtmlLink> _tblHtmlLinks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblPage> tblPages
        {
            get
            {
                if ((_tblPages == null))
                {
                    _tblPages = base.CreateObjectSet<tblPage>("tblPages");
                }
                return _tblPages;
            }
        }
        private ObjectSet<tblPage> _tblPages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSearchSession> tblSearchSessions
        {
            get
            {
                if ((_tblSearchSessions == null))
                {
                    _tblSearchSessions = base.CreateObjectSet<tblSearchSession>("tblSearchSessions");
                }
                return _tblSearchSessions;
            }
        }
        private ObjectSet<tblSearchSession> _tblSearchSessions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblVehicle> tblVehicles
        {
            get
            {
                if ((_tblVehicles == null))
                {
                    _tblVehicles = base.CreateObjectSet<tblVehicle>("tblVehicles");
                }
                return _tblVehicles;
            }
        }
        private ObjectSet<tblVehicle> _tblVehicles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblVehicleTypeCountry> tblVehicleTypeCountries
        {
            get
            {
                if ((_tblVehicleTypeCountries == null))
                {
                    _tblVehicleTypeCountries = base.CreateObjectSet<tblVehicleTypeCountry>("tblVehicleTypeCountries");
                }
                return _tblVehicleTypeCountries;
            }
        }
        private ObjectSet<tblVehicleTypeCountry> _tblVehicleTypeCountries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblVehicleTypeDefined> tblVehicleTypeDefineds
        {
            get
            {
                if ((_tblVehicleTypeDefineds == null))
                {
                    _tblVehicleTypeDefineds = base.CreateObjectSet<tblVehicleTypeDefined>("tblVehicleTypeDefineds");
                }
                return _tblVehicleTypeDefineds;
            }
        }
        private ObjectSet<tblVehicleTypeDefined> _tblVehicleTypeDefineds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblVehicleTypeGeneral> tblVehicleTypeGenerals
        {
            get
            {
                if ((_tblVehicleTypeGenerals == null))
                {
                    _tblVehicleTypeGenerals = base.CreateObjectSet<tblVehicleTypeGeneral>("tblVehicleTypeGenerals");
                }
                return _tblVehicleTypeGenerals;
            }
        }
        private ObjectSet<tblVehicleTypeGeneral> _tblVehicleTypeGenerals;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblHtmls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblHtmls(tblHtml tblHtml)
        {
            base.AddObject("tblHtmls", tblHtml);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblHtmlLinks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblHtmlLinks(tblHtmlLink tblHtmlLink)
        {
            base.AddObject("tblHtmlLinks", tblHtmlLink);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblPages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblPages(tblPage tblPage)
        {
            base.AddObject("tblPages", tblPage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSearchSessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSearchSessions(tblSearchSession tblSearchSession)
        {
            base.AddObject("tblSearchSessions", tblSearchSession);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblVehicles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblVehicles(tblVehicle tblVehicle)
        {
            base.AddObject("tblVehicles", tblVehicle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblVehicleTypeCountries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblVehicleTypeCountries(tblVehicleTypeCountry tblVehicleTypeCountry)
        {
            base.AddObject("tblVehicleTypeCountries", tblVehicleTypeCountry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblVehicleTypeDefineds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblVehicleTypeDefineds(tblVehicleTypeDefined tblVehicleTypeDefined)
        {
            base.AddObject("tblVehicleTypeDefineds", tblVehicleTypeDefined);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblVehicleTypeGenerals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblVehicleTypeGenerals(tblVehicleTypeGeneral tblVehicleTypeGeneral)
        {
            base.AddObject("tblVehicleTypeGenerals", tblVehicleTypeGeneral);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblHtml")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblHtml : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblHtml object.
        /// </summary>
        /// <param name="html_id_pk">Initial value of the html_id_pk property.</param>
        public static tblHtml CreatetblHtml(global::System.Int32 html_id_pk)
        {
            tblHtml tblHtml = new tblHtml();
            tblHtml.html_id_pk = html_id_pk;
            return tblHtml;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 html_id_pk
        {
            get
            {
                return _html_id_pk;
            }
            set
            {
                if (_html_id_pk != value)
                {
                    Onhtml_id_pkChanging(value);
                    ReportPropertyChanging("html_id_pk");
                    _html_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("html_id_pk");
                    Onhtml_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _html_id_pk;
        partial void Onhtml_id_pkChanging(global::System.Int32 value);
        partial void Onhtml_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String html_data
        {
            get
            {
                return _html_data;
            }
            set
            {
                Onhtml_dataChanging(value);
                ReportPropertyChanging("html_data");
                _html_data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("html_data");
                Onhtml_dataChanged();
            }
        }
        private global::System.String _html_data;
        partial void Onhtml_dataChanging(global::System.String value);
        partial void Onhtml_dataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Vehicle_id_fk
        {
            get
            {
                return _Vehicle_id_fk;
            }
            set
            {
                OnVehicle_id_fkChanging(value);
                ReportPropertyChanging("Vehicle_id_fk");
                _Vehicle_id_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vehicle_id_fk");
                OnVehicle_id_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _Vehicle_id_fk;
        partial void OnVehicle_id_fkChanging(Nullable<global::System.Int32> value);
        partial void OnVehicle_id_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Search_Date_Timestamp
        {
            get
            {
                return _Search_Date_Timestamp;
            }
            set
            {
                OnSearch_Date_TimestampChanging(value);
                ReportPropertyChanging("Search_Date_Timestamp");
                _Search_Date_Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Search_Date_Timestamp");
                OnSearch_Date_TimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _Search_Date_Timestamp;
        partial void OnSearch_Date_TimestampChanging(Nullable<global::System.DateTime> value);
        partial void OnSearch_Date_TimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Search_Session_ID_fk
        {
            get
            {
                return _Search_Session_ID_fk;
            }
            set
            {
                OnSearch_Session_ID_fkChanging(value);
                ReportPropertyChanging("Search_Session_ID_fk");
                _Search_Session_ID_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Search_Session_ID_fk");
                OnSearch_Session_ID_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _Search_Session_ID_fk;
        partial void OnSearch_Session_ID_fkChanging(Nullable<global::System.Int32> value);
        partial void OnSearch_Session_ID_fkChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblHtml_tblSearchSession", "tblSearchSession")]
        public tblSearchSession tblSearchSession
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSearchSession>("seleniumScrapeModel.FK_tblHtml_tblSearchSession", "tblSearchSession").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSearchSession>("seleniumScrapeModel.FK_tblHtml_tblSearchSession", "tblSearchSession").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblSearchSession> tblSearchSessionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSearchSession>("seleniumScrapeModel.FK_tblHtml_tblSearchSession", "tblSearchSession");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblSearchSession>("seleniumScrapeModel.FK_tblHtml_tblSearchSession", "tblSearchSession", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblHtml_tblVehicle1", "tblVehicle")]
        public tblVehicle tblVehicle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicle>("seleniumScrapeModel.FK_tblHtml_tblVehicle1", "tblVehicle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicle>("seleniumScrapeModel.FK_tblHtml_tblVehicle1", "tblVehicle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblVehicle> tblVehicleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicle>("seleniumScrapeModel.FK_tblHtml_tblVehicle1", "tblVehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblVehicle>("seleniumScrapeModel.FK_tblHtml_tblVehicle1", "tblVehicle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblHtmlLink_tblHtml", "tblHtmlLink")]
        public EntityCollection<tblHtmlLink> tblHtmlLinks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblHtmlLink>("seleniumScrapeModel.FK_tblHtmlLink_tblHtml", "tblHtmlLink");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblHtmlLink>("seleniumScrapeModel.FK_tblHtmlLink_tblHtml", "tblHtmlLink", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblHtmlLink")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblHtmlLink : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblHtmlLink object.
        /// </summary>
        /// <param name="html_Link_ID_PK">Initial value of the html_Link_ID_PK property.</param>
        public static tblHtmlLink CreatetblHtmlLink(global::System.Int32 html_Link_ID_PK)
        {
            tblHtmlLink tblHtmlLink = new tblHtmlLink();
            tblHtmlLink.html_Link_ID_PK = html_Link_ID_PK;
            return tblHtmlLink;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 html_Link_ID_PK
        {
            get
            {
                return _html_Link_ID_PK;
            }
            set
            {
                if (_html_Link_ID_PK != value)
                {
                    Onhtml_Link_ID_PKChanging(value);
                    ReportPropertyChanging("html_Link_ID_PK");
                    _html_Link_ID_PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("html_Link_ID_PK");
                    Onhtml_Link_ID_PKChanged();
                }
            }
        }
        private global::System.Int32 _html_Link_ID_PK;
        partial void Onhtml_Link_ID_PKChanging(global::System.Int32 value);
        partial void Onhtml_Link_ID_PKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> html_data_ID_fk
        {
            get
            {
                return _html_data_ID_fk;
            }
            set
            {
                Onhtml_data_ID_fkChanging(value);
                ReportPropertyChanging("html_data_ID_fk");
                _html_data_ID_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("html_data_ID_fk");
                Onhtml_data_ID_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _html_data_ID_fk;
        partial void Onhtml_data_ID_fkChanging(Nullable<global::System.Int32> value);
        partial void Onhtml_data_ID_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> html_link_order_position_number
        {
            get
            {
                return _html_link_order_position_number;
            }
            set
            {
                Onhtml_link_order_position_numberChanging(value);
                ReportPropertyChanging("html_link_order_position_number");
                _html_link_order_position_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("html_link_order_position_number");
                Onhtml_link_order_position_numberChanged();
            }
        }
        private Nullable<global::System.Int32> _html_link_order_position_number;
        partial void Onhtml_link_order_position_numberChanging(Nullable<global::System.Int32> value);
        partial void Onhtml_link_order_position_numberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblHtmlLink_tblHtml", "tblHtml")]
        public tblHtml tblHtml
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblHtml>("seleniumScrapeModel.FK_tblHtmlLink_tblHtml", "tblHtml").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblHtml>("seleniumScrapeModel.FK_tblHtmlLink_tblHtml", "tblHtml").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblHtml> tblHtmlReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblHtml>("seleniumScrapeModel.FK_tblHtmlLink_tblHtml", "tblHtml");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblHtml>("seleniumScrapeModel.FK_tblHtmlLink_tblHtml", "tblHtml", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblPage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblPage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblPage object.
        /// </summary>
        /// <param name="page_id_pk">Initial value of the page_id_pk property.</param>
        public static tblPage CreatetblPage(global::System.Int32 page_id_pk)
        {
            tblPage tblPage = new tblPage();
            tblPage.page_id_pk = page_id_pk;
            return tblPage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Vehicle_ID_fk
        {
            get
            {
                return _Vehicle_ID_fk;
            }
            set
            {
                OnVehicle_ID_fkChanging(value);
                ReportPropertyChanging("Vehicle_ID_fk");
                _Vehicle_ID_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vehicle_ID_fk");
                OnVehicle_ID_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _Vehicle_ID_fk;
        partial void OnVehicle_ID_fkChanging(Nullable<global::System.Int32> value);
        partial void OnVehicle_ID_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 page_id_pk
        {
            get
            {
                return _page_id_pk;
            }
            set
            {
                if (_page_id_pk != value)
                {
                    Onpage_id_pkChanging(value);
                    ReportPropertyChanging("page_id_pk");
                    _page_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("page_id_pk");
                    Onpage_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _page_id_pk;
        partial void Onpage_id_pkChanging(global::System.Int32 value);
        partial void Onpage_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Search_Date_Timestamp
        {
            get
            {
                return _Search_Date_Timestamp;
            }
            set
            {
                OnSearch_Date_TimestampChanging(value);
                ReportPropertyChanging("Search_Date_Timestamp");
                _Search_Date_Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Search_Date_Timestamp");
                OnSearch_Date_TimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _Search_Date_Timestamp;
        partial void OnSearch_Date_TimestampChanging(Nullable<global::System.DateTime> value);
        partial void OnSearch_Date_TimestampChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblPage_tblVehicle", "tblVehicle")]
        public tblVehicle tblVehicle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicle>("seleniumScrapeModel.FK_tblPage_tblVehicle", "tblVehicle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicle>("seleniumScrapeModel.FK_tblPage_tblVehicle", "tblVehicle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblVehicle> tblVehicleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicle>("seleniumScrapeModel.FK_tblPage_tblVehicle", "tblVehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblVehicle>("seleniumScrapeModel.FK_tblPage_tblVehicle", "tblVehicle", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblSearchSession")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSearchSession : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSearchSession object.
        /// </summary>
        /// <param name="search_Session_ID_PK">Initial value of the Search_Session_ID_PK property.</param>
        public static tblSearchSession CreatetblSearchSession(global::System.Int32 search_Session_ID_PK)
        {
            tblSearchSession tblSearchSession = new tblSearchSession();
            tblSearchSession.Search_Session_ID_PK = search_Session_ID_PK;
            return tblSearchSession;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Search_Session_ID_PK
        {
            get
            {
                return _Search_Session_ID_PK;
            }
            set
            {
                if (_Search_Session_ID_PK != value)
                {
                    OnSearch_Session_ID_PKChanging(value);
                    ReportPropertyChanging("Search_Session_ID_PK");
                    _Search_Session_ID_PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Search_Session_ID_PK");
                    OnSearch_Session_ID_PKChanged();
                }
            }
        }
        private global::System.Int32 _Search_Session_ID_PK;
        partial void OnSearch_Session_ID_PKChanging(global::System.Int32 value);
        partial void OnSearch_Session_ID_PKChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblHtml_tblSearchSession", "tblHtml")]
        public EntityCollection<tblHtml> tblHtmls
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblHtml>("seleniumScrapeModel.FK_tblHtml_tblSearchSession", "tblHtml");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblHtml>("seleniumScrapeModel.FK_tblHtml_tblSearchSession", "tblHtml", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblVehicle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblVehicle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblVehicle object.
        /// </summary>
        /// <param name="vehicle_ID_Pk">Initial value of the Vehicle_ID_Pk property.</param>
        public static tblVehicle CreatetblVehicle(global::System.Int32 vehicle_ID_Pk)
        {
            tblVehicle tblVehicle = new tblVehicle();
            tblVehicle.Vehicle_ID_Pk = vehicle_ID_Pk;
            return tblVehicle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Vehicle_Type_General_id_fk
        {
            get
            {
                return _Vehicle_Type_General_id_fk;
            }
            set
            {
                OnVehicle_Type_General_id_fkChanging(value);
                ReportPropertyChanging("Vehicle_Type_General_id_fk");
                _Vehicle_Type_General_id_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vehicle_Type_General_id_fk");
                OnVehicle_Type_General_id_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _Vehicle_Type_General_id_fk;
        partial void OnVehicle_Type_General_id_fkChanging(Nullable<global::System.Int32> value);
        partial void OnVehicle_Type_General_id_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Vehicle_Type_Defined_fk
        {
            get
            {
                return _Vehicle_Type_Defined_fk;
            }
            set
            {
                OnVehicle_Type_Defined_fkChanging(value);
                ReportPropertyChanging("Vehicle_Type_Defined_fk");
                _Vehicle_Type_Defined_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vehicle_Type_Defined_fk");
                OnVehicle_Type_Defined_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _Vehicle_Type_Defined_fk;
        partial void OnVehicle_Type_Defined_fkChanging(Nullable<global::System.Int32> value);
        partial void OnVehicle_Type_Defined_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Vehicle_ID_Pk
        {
            get
            {
                return _Vehicle_ID_Pk;
            }
            set
            {
                if (_Vehicle_ID_Pk != value)
                {
                    OnVehicle_ID_PkChanging(value);
                    ReportPropertyChanging("Vehicle_ID_Pk");
                    _Vehicle_ID_Pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Vehicle_ID_Pk");
                    OnVehicle_ID_PkChanged();
                }
            }
        }
        private global::System.Int32 _Vehicle_ID_Pk;
        partial void OnVehicle_ID_PkChanging(global::System.Int32 value);
        partial void OnVehicle_ID_PkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vehicle_Make
        {
            get
            {
                return _Vehicle_Make;
            }
            set
            {
                OnVehicle_MakeChanging(value);
                ReportPropertyChanging("Vehicle_Make");
                _Vehicle_Make = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vehicle_Make");
                OnVehicle_MakeChanged();
            }
        }
        private global::System.String _Vehicle_Make;
        partial void OnVehicle_MakeChanging(global::System.String value);
        partial void OnVehicle_MakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vehicle_Model
        {
            get
            {
                return _Vehicle_Model;
            }
            set
            {
                OnVehicle_ModelChanging(value);
                ReportPropertyChanging("Vehicle_Model");
                _Vehicle_Model = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vehicle_Model");
                OnVehicle_ModelChanged();
            }
        }
        private global::System.String _Vehicle_Model;
        partial void OnVehicle_ModelChanging(global::System.String value);
        partial void OnVehicle_ModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Vehicle_Type_ID_fk
        {
            get
            {
                return _Vehicle_Type_ID_fk;
            }
            set
            {
                OnVehicle_Type_ID_fkChanging(value);
                ReportPropertyChanging("Vehicle_Type_ID_fk");
                _Vehicle_Type_ID_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vehicle_Type_ID_fk");
                OnVehicle_Type_ID_fkChanged();
            }
        }
        private Nullable<global::System.Int32> _Vehicle_Type_ID_fk;
        partial void OnVehicle_Type_ID_fkChanging(Nullable<global::System.Int32> value);
        partial void OnVehicle_Type_ID_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Vehicle_WillBeSearched
        {
            get
            {
                return _Vehicle_WillBeSearched;
            }
            set
            {
                OnVehicle_WillBeSearchedChanging(value);
                ReportPropertyChanging("Vehicle_WillBeSearched");
                _Vehicle_WillBeSearched = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vehicle_WillBeSearched");
                OnVehicle_WillBeSearchedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Vehicle_WillBeSearched;
        partial void OnVehicle_WillBeSearchedChanging(Nullable<global::System.Boolean> value);
        partial void OnVehicle_WillBeSearchedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblHtml_tblVehicle1", "tblHtml")]
        public EntityCollection<tblHtml> tblHtmls
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblHtml>("seleniumScrapeModel.FK_tblHtml_tblVehicle1", "tblHtml");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblHtml>("seleniumScrapeModel.FK_tblHtml_tblVehicle1", "tblHtml", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblPage_tblVehicle", "tblPage")]
        public EntityCollection<tblPage> tblPages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblPage>("seleniumScrapeModel.FK_tblPage_tblVehicle", "tblPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblPage>("seleniumScrapeModel.FK_tblPage_tblVehicle", "tblPage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleType", "tblVehicleTypeCountry")]
        public tblVehicleTypeCountry tblVehicleTypeCountry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeCountry>("seleniumScrapeModel.FK_tblVehicle_tblVehicleType", "tblVehicleTypeCountry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeCountry>("seleniumScrapeModel.FK_tblVehicle_tblVehicleType", "tblVehicleTypeCountry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblVehicleTypeCountry> tblVehicleTypeCountryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeCountry>("seleniumScrapeModel.FK_tblVehicle_tblVehicleType", "tblVehicleTypeCountry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblVehicleTypeCountry>("seleniumScrapeModel.FK_tblVehicle_tblVehicleType", "tblVehicleTypeCountry", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleTypeDefined", "tblVehicleTypeDefined")]
        public tblVehicleTypeDefined tblVehicleTypeDefined
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeDefined>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeDefined", "tblVehicleTypeDefined").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeDefined>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeDefined", "tblVehicleTypeDefined").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblVehicleTypeDefined> tblVehicleTypeDefinedReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeDefined>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeDefined", "tblVehicleTypeDefined");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblVehicleTypeDefined>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeDefined", "tblVehicleTypeDefined", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicleTypeGeneral")]
        public tblVehicleTypeGeneral tblVehicleTypeGeneral
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeGeneral>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicleTypeGeneral").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeGeneral>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicleTypeGeneral").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblVehicleTypeGeneral> tblVehicleTypeGeneralReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblVehicleTypeGeneral>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicleTypeGeneral");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblVehicleTypeGeneral>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicleTypeGeneral", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblVehicleTypeCountry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblVehicleTypeCountry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblVehicleTypeCountry object.
        /// </summary>
        /// <param name="vehicle_Type_Country_ID_pk">Initial value of the Vehicle_Type_Country_ID_pk property.</param>
        public static tblVehicleTypeCountry CreatetblVehicleTypeCountry(global::System.Int32 vehicle_Type_Country_ID_pk)
        {
            tblVehicleTypeCountry tblVehicleTypeCountry = new tblVehicleTypeCountry();
            tblVehicleTypeCountry.Vehicle_Type_Country_ID_pk = vehicle_Type_Country_ID_pk;
            return tblVehicleTypeCountry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Vehicle_Type_Country_ID_pk
        {
            get
            {
                return _Vehicle_Type_Country_ID_pk;
            }
            set
            {
                if (_Vehicle_Type_Country_ID_pk != value)
                {
                    OnVehicle_Type_Country_ID_pkChanging(value);
                    ReportPropertyChanging("Vehicle_Type_Country_ID_pk");
                    _Vehicle_Type_Country_ID_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Vehicle_Type_Country_ID_pk");
                    OnVehicle_Type_Country_ID_pkChanged();
                }
            }
        }
        private global::System.Int32 _Vehicle_Type_Country_ID_pk;
        partial void OnVehicle_Type_Country_ID_pkChanging(global::System.Int32 value);
        partial void OnVehicle_Type_Country_ID_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vehicle_Type_Country
        {
            get
            {
                return _Vehicle_Type_Country;
            }
            set
            {
                OnVehicle_Type_CountryChanging(value);
                ReportPropertyChanging("Vehicle_Type_Country");
                _Vehicle_Type_Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vehicle_Type_Country");
                OnVehicle_Type_CountryChanged();
            }
        }
        private global::System.String _Vehicle_Type_Country;
        partial void OnVehicle_Type_CountryChanging(global::System.String value);
        partial void OnVehicle_Type_CountryChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleType", "tblVehicle")]
        public EntityCollection<tblVehicle> tblVehicles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblVehicle>("seleniumScrapeModel.FK_tblVehicle_tblVehicleType", "tblVehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblVehicle>("seleniumScrapeModel.FK_tblVehicle_tblVehicleType", "tblVehicle", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblVehicleTypeDefined")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblVehicleTypeDefined : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblVehicleTypeDefined object.
        /// </summary>
        /// <param name="vehicleTypeDefined_id_pk">Initial value of the VehicleTypeDefined_id_pk property.</param>
        public static tblVehicleTypeDefined CreatetblVehicleTypeDefined(global::System.Int32 vehicleTypeDefined_id_pk)
        {
            tblVehicleTypeDefined tblVehicleTypeDefined = new tblVehicleTypeDefined();
            tblVehicleTypeDefined.VehicleTypeDefined_id_pk = vehicleTypeDefined_id_pk;
            return tblVehicleTypeDefined;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VehicleTypeDefined_id_pk
        {
            get
            {
                return _VehicleTypeDefined_id_pk;
            }
            set
            {
                if (_VehicleTypeDefined_id_pk != value)
                {
                    OnVehicleTypeDefined_id_pkChanging(value);
                    ReportPropertyChanging("VehicleTypeDefined_id_pk");
                    _VehicleTypeDefined_id_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VehicleTypeDefined_id_pk");
                    OnVehicleTypeDefined_id_pkChanged();
                }
            }
        }
        private global::System.Int32 _VehicleTypeDefined_id_pk;
        partial void OnVehicleTypeDefined_id_pkChanging(global::System.Int32 value);
        partial void OnVehicleTypeDefined_id_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VehicleTypeDefined
        {
            get
            {
                return _VehicleTypeDefined;
            }
            set
            {
                OnVehicleTypeDefinedChanging(value);
                ReportPropertyChanging("VehicleTypeDefined");
                _VehicleTypeDefined = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VehicleTypeDefined");
                OnVehicleTypeDefinedChanged();
            }
        }
        private global::System.String _VehicleTypeDefined;
        partial void OnVehicleTypeDefinedChanging(global::System.String value);
        partial void OnVehicleTypeDefinedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleTypeDefined", "tblVehicle")]
        public EntityCollection<tblVehicle> tblVehicles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblVehicle>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeDefined", "tblVehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblVehicle>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeDefined", "tblVehicle", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="seleniumScrapeModel", Name="tblVehicleTypeGeneral")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblVehicleTypeGeneral : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblVehicleTypeGeneral object.
        /// </summary>
        /// <param name="vehicleTypeGeneral_pk">Initial value of the VehicleTypeGeneral_pk property.</param>
        public static tblVehicleTypeGeneral CreatetblVehicleTypeGeneral(global::System.Int32 vehicleTypeGeneral_pk)
        {
            tblVehicleTypeGeneral tblVehicleTypeGeneral = new tblVehicleTypeGeneral();
            tblVehicleTypeGeneral.VehicleTypeGeneral_pk = vehicleTypeGeneral_pk;
            return tblVehicleTypeGeneral;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VehicleTypeGeneral_pk
        {
            get
            {
                return _VehicleTypeGeneral_pk;
            }
            set
            {
                if (_VehicleTypeGeneral_pk != value)
                {
                    OnVehicleTypeGeneral_pkChanging(value);
                    ReportPropertyChanging("VehicleTypeGeneral_pk");
                    _VehicleTypeGeneral_pk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VehicleTypeGeneral_pk");
                    OnVehicleTypeGeneral_pkChanged();
                }
            }
        }
        private global::System.Int32 _VehicleTypeGeneral_pk;
        partial void OnVehicleTypeGeneral_pkChanging(global::System.Int32 value);
        partial void OnVehicleTypeGeneral_pkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VehicleTypeGeneral
        {
            get
            {
                return _VehicleTypeGeneral;
            }
            set
            {
                OnVehicleTypeGeneralChanging(value);
                ReportPropertyChanging("VehicleTypeGeneral");
                _VehicleTypeGeneral = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VehicleTypeGeneral");
                OnVehicleTypeGeneralChanged();
            }
        }
        private global::System.String _VehicleTypeGeneral;
        partial void OnVehicleTypeGeneralChanging(global::System.String value);
        partial void OnVehicleTypeGeneralChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("seleniumScrapeModel", "FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicle")]
        public EntityCollection<tblVehicle> tblVehicles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblVehicle>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblVehicle>("seleniumScrapeModel.FK_tblVehicle_tblVehicleTypeGeneral", "tblVehicle", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
